version: "3.2"
services:

  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: unless-stopped
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - ./front:/app
    env_file:
      - front/.env
    entrypoint: /app/entrypoint.sh
    networks:
      - rabbitmq_network1

  # python_alpine:
  #   container_name: 'python_alpine'
  #   build: .
  #   restart: unless-stopped
  #   # ports:
  #   #     - 7000:5000
  #   volumes:
  #       - ./scripts:/scripts
  #   networks:
  #       - rabbitmq_network1
  
  django:
    container_name: 'django'
    build:
      context: ./django
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=psql://postgres:postgres@postgres:5432/crypto
      - DATABASE_HOST=172.40.0.20
      - DATABASE_HOST_LIST=172.40.0.20,172.40.0.21,172.40.0.22
      - RABBITMQ_HOST=172.40.0.30
      - RABBITMQ_HOST_LIST=172.40.0.30,172.40.0.31,,172.40.0.32
      - SOURCE_ID=postgres_env1
    command: sh -c "./entrypoint.sh"
    ports:
        - 5000:5000
    volumes:
        - ./django:/code
    networks:
        - rabbitmq_network1

  rabbitmq_node10:
    hostname: rabbitmq_node10
    image: rabbitmq:management
    container_name: rabbitmq_node10
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        - ./rabbitmq:/host
    # entrypoint: /host/entrypoint.sh
    environment:
        - RABBITMQ_ERLANG_COOKIE=rabbitcookie
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin
    extra_hosts:
      - "rabbitmq_node20:172.40.0.31"
      - "rabbitmq_node30:172.40.0.32"
    networks:
        - rabbitmq_network1
  
  rabbitmq-client:
    container_name: 'rabbitmq-client'
    build:
      context: ./rabbitmq_client
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_HOST=172.40.0.20
      - RABBITMQ_HOST=172.40.0.30
      - RABBITMQ_HOST_LIST=172.40.0.30,172.40.0.31,172.40.0.32
      - RABBITMQ_QUEUE=crypto1
      - RABBITMQ_ROUTING_KEY=key_crypto1
      - RABBITMQ_ROUTING_KEY_LIST=key_crypto1,key_crypto2,key_crypto3
      - SOURCE_ID=postgres_env1
    command: sh -c "./entrypoint.sh"
    volumes:
        - ./rabbitmq_client:/code
    networks:
        - rabbitmq_network1

  # adminer:
  #   image: adminer
  #   container_name: 'adminer'
  #   ports:
  #       - 8089:8080
  #   restart: unless-stopped
  #   networks:
  #       - rabbitmq_network1


  postgres:
    image: postgres:14.8
    container_name: 'postgres'
    restart: unless-stopped
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=crypto
        - POSTGRES_HOST_AUTH_METHOD=md5
    command: postgres -c max_connections=20000 -c shared_buffers=1GB -c password_encryption=scram-sha-256
    volumes:
        - postgresql:/var/lib/postgresql/data
        - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432
    networks:
        - rabbitmq_network1

volumes:
    postgresql:

networks:
  rabbitmq_network1:
    driver: bridge